config/routes.rb
Rails.application.routes.draw do
  resources :direct_treasuries
  resources :exchanges
  
  resources :stocks do
    member do
      get :stocks_movimentation
    end
    
    collection do
      get :stocks_list
    end
  end
  
  resources :investment_funds
  resources :wallets do
    resources :investment_funds
  end 
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  root to: 'pages#home'
  get '/home', to: 'pages#home', as: :home

  get "/direct_treasuries/simulate/:id" => "direct_treasuries#simulate", :as => 'simulate_direct_treasury'
  get "/analysis/index " => "analysis#index", :as => 'analysis_index'
  get "/questionnaire/index" => "questionnaire#index", :as => 'questionnaire_index'
  post "/questionnaire/questionnaire_result" => "questionnaire#questionnaire_result", :as => 'questionnaire_result'
  get "/questionnaire/user_investment_profile" => "questionnaire#user_investment_profile", :as => 'investment_profile_result'	
  

end

app/models/investment_fund.rb
class InvestmentFund < ActiveRecord::Base
  belongs_to :wallet

  def share_value
    share_value = self[:capital]/self[:exitTax]
    return format("%.2f", share_value).to_f
  end

  def number_share
    number_share = self[:shareValue]/share_value
    return format("%.2f", number_share).to_f
  end

  def total_fund_share
    total_fund_share = self[:exitTax]+number_share
    return format("%.2f", total_fund_share).to_f
  end

  def net_worth
    net_worth = self[:capital]+self[:shareValue]
    return format("%.2f", net_worth).to_f
  end

  def dimension_values
    dimension_values = net_worth/total_fund_share
    return format("%.2f", dimension_values).to_f
  end

  def yield_percentage
    yield_percentage = dimension_values/share_value * self[:admTax]
    return yield_percentage
  end
  
end

app/controllers/investment_funds_controller.rb
class InvestmentFundsController < ApplicationController
  before_action :set_investment_fund, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /investment_funds
  # GET /investment_funds.json
  def index
    @wallet_id = params[:wallet_id]
    @investment_funds = InvestmentFund.where("wallet_id = ?", @wallet_id)
  end

  # GET /investment_funds/1
  # GET /investment_funds/1.json
  def show
  end

  # GET /investment_funds/new
  def new
    @investment_fund = InvestmentFund.new
  end

  # GET /investment_funds/1/edit
  def edit
  end

  # POST /investment_funds
  # POST /investment_funds.json
  def create
    @investment_fund = InvestmentFund.new(investment_fund_params)

    respond_to do |format|
      if @investment_fund.save
        format.html { redirect_to @investment_fund, notice: 'Investment fund was successfully created.' }
        format.json { render :show, status: :created, location: @investment_fund }
      else
        format.html { render :new }
        format.json { render json: @investment_fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investment_funds/1
  # PATCH/PUT /investment_funds/1.json
  def update
    respond_to do |format|
      if @investment_fund.update(investment_fund_params)
        format.html { redirect_to @investment_fund, notice: 'Investment fund was successfully updated.' }
        format.json { render :show, status: :ok, location: @investment_fund }
      else
        format.html { render :edit }
        format.json { render json: @investment_fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investment_funds/1
  # DELETE /investment_funds/1.json
  def destroy
    @investment_fund.destroy
    respond_to do |format|
      format.html { redirect_to wallets_path, notice: 'Investment fund was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_investment_fund
      @investment_fund = InvestmentFund.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def investment_fund_params
      params.require(:investment_fund).permit(:name, :buyDate, :admTax, :aditionalInfo, :exitTax, :fundBegin, :manager, :managerContact, :shareValue, :capital, :wallet_id)
    end
end

app/helpers/investment_funds_helper.rb
module InvestmentFundsHelper
end

app/views/investment_funds/_form.html.erb
<%= form_for(@investment_fund) do |f| %>
  <% if @investment_fund.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@investment_fund.errors.count, "error") %> prohibited this investment_fund from being saved:</h2>

      <ul>
      <% @investment_fund.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nome %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Data_de_Investimento %><br>
    <%= f.date_select :buyDate %>
  </div>
  <div class="field">
    <%= f.label :admTax, "Taxa Administrativa" %><br>
    <%= f.number_field :admTax, :step => 0.01 %>
  </div>
  <div class="field">
    <%= f.label :capital, "Patrimônio Inicial" %><br>
    <%= f.number_field :capital, :step => 0.01 %>
  </div>
  <div class="field">
    <%= f.label :shareValue, "Investimento" %><br>
    <%= f.number_field :shareValue, :step => 0.01 %>
  </div>
  <div class="field">
    <%= f.label :exitTax, "Cotas Iniciais" %><br>
    <%= f.number_field :exitTax, :step => 1.0 %>
  </div>
  <div class="field">
    <%= f.label :Gerente_do_Investimento %><br>
    <%= f.text_field :manager %>
  </div>
  <div class="field">
    <%= f.label :Contato_do_Gerente %><br>
    <%= f.text_field :managerContact %>
  </div>
  <div class="field">
    <%= f.label :wallet_id, "Carteira" %><br>
    <%= f.number_field :wallet_id %>
  </div>
  <div class="actions">
    <%= f.submit "Enviar" %>
  </div>
<% end %>

app/views/investment_funds/edit.html.erb
<h1>Editar Fundo de Investmento</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @investment_fund %> |
<%= link_to 'Voltar', wallets_path %>

app/views/investment_funds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fundo de Investimento</h1>

<table>
  <thead>
    <tr>
      <th>Carteira</th>
      <th>Nome</th>
      <th>Data de Inv.</th>
      <th>Taxa Administ.</th>
      <th>Patrimônio Inic.</th>
      <th>Investimento</th>
      <th>Cotas Inic.</th>
      <th>Gerente</th>
      <th>Contato</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @investment_funds.each do |investment_fund| %>
      <tr>
        <td><%= investment_fund.wallet.name %></td>
        <td><%= investment_fund.name %></td>
        <td><%= investment_fund.buyDate %></td>
        <td><%= investment_fund.admTax %></td>
        <td><%= investment_fund.capital %></td>
        <td><%= investment_fund.shareValue %></td>
        <td><%= investment_fund.exitTax %></td>
        <td><%= investment_fund.manager %></td>
        <td><%= investment_fund.managerContact %></td>
        <td><%= link_to 'Exibir', investment_fund %></td>
        <td><%= link_to 'Editar', edit_investment_fund_path(investment_fund) %></td>
        <td><%= link_to 'Apagar', investment_fund, method: :delete, data: { confirm: 'Tem Certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Fundo de Investimento', new_investment_fund_path %>
<br>
<%= link_to 'Voltar', wallets_path %>

app/views/investment_funds/new.html.erb
<h1>Novo Fundo de Investimento</h1>

<%= render 'form' %>

<%= link_to 'Voltar', wallets_path %>

app/views/investment_funds/show.html.erb
 
<p id="notice"><%= notice %></p>

<p>
  <strong>Carteira:</strong>
  <%= @investment_fund.wallet.name %>
</p>

<p>
  <strong>Nome do Fundo de Investimento:</strong>
  <%= @investment_fund.name %>
</p>

<p>
  <strong>Data da Compra:</strong>
  <%= @investment_fund.buyDate %>
</p>

<p>
  <strong>Taxa Administrativa:</strong>
  <%= @investment_fund.admTax %>
</p>

<p>
  <strong>Patrimônio Inicial:</strong>
  <%= @investment_fund.capital %>
</p>

<p>
  <strong>Investimento:</strong>
  <%= @investment_fund.shareValue %>
</p>

<p>
  <strong>Cotas Iniciais:</strong>
  <%= @investment_fund.exitTax.to_i %>
</p>

<p>
  <strong>Gerente do Investimento:</strong>
  <%= @investment_fund.manager %>
</p>

<p>
  <strong>Contato do Gerente:</strong>
  <%= @investment_fund.managerContact %>
</p>

<p>
  <strong>Valor da cota na data da aplicação:</strong>
  <%= @investment_fund.share_value %>
</p>

<p>
  <strong>Número de cotas adquiridas pelo investidor:</strong>
  <%= @investment_fund.number_share.to_i %>
</p>

<p>
  <strong>Total de cotas do fundo após a aplicação:</strong>
  <%= @investment_fund.total_fund_share.to_i %>
</p>

<p>
  <strong>Patrimônio Líquido após a aplicação:</strong>
  <%= @investment_fund.net_worth %>
</p>

<p>
  <strong>Valor da cota após a aplicação:</strong>
  <%= @investment_fund.dimension_values %>
</p>

<p>
  <strong>Percentual de Rentabilidade:</strong>
  <%= @investment_fund.yield_percentage.to_i %>%
</p>


<%= link_to 'Editar', edit_investment_fund_path(@investment_fund),  class: 'button info tiny' %> |
<%= link_to 'Voltar', wallets_path,  class: 'button info tiny' %>