config/routes.rb
Rails.application.routes.draw do
  resources :direct_treasuries
  resources :exchanges
  
  resources :stocks do
    member do
      get :stocks_movimentation
    end
    
    collection do
      get :stocks_list
    end
  end
  
  resources :investment_funds
  resources :wallets do
    resources :investment_funds
  end 
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  root to: 'pages#home'
  get '/home', to: 'pages#home', as: :home

  get "/direct_treasuries/simulate/:id" => "direct_treasuries#simulate", :as => 'simulate_direct_treasury'
  get "/analysis/index " => "analysis#index", :as => 'analysis_index'
  get "/questionnaire/index" => "questionnaire#index", :as => 'questionnaire_index'
  post "/questionnaire/questionnaire_result" => "questionnaire#questionnaire_result", :as => 'questionnaire_result'
  get "/questionnaire/user_investment_profile" => "questionnaire#user_investment_profile", :as => 'investment_profile_result'	
  

end

app/models/exchange.rb
class Exchange < ActiveRecord::Base
  belongs_to :wallet
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  before_action :set_exchange, only: [:show, :edit, :update, :destroy]
  helper_method :discount, :convert, :convert_current_income
  before_action :authenticate_user!

  # GET /exchanges
  def index
    @wallet_id = params[:wallet_id]
    @exchanges = Exchange.where("wallet_id = ?", @wallet_id)
  end

  # GET /exchanges/1
  def show
  end

  def convert
    if @exchange[:exchange_type] == "Dolar"
      dollar_quotation = @exchange[:initial_dollar_quotation]
      initial_income = @exchange[:initial_income] 
      reais = dollar_quotation*initial_income
    elsif @exchange[:exchange_type] == "Euro"
      euro_quotation = @exchange[:initial_euro_quotation]
      initial_income = @exchange[:initial_income]
      reais = euro_quotation*initial_income
    end
    return reais
  end

  def convert_current_income
    json_request
    if @exchange[:exchange_type] == "Dolar"
      dollar_quotation = @exchange[:dollar_quotation]
      initial_income = @exchange[:initial_income] 
      reais = dollar_quotation*initial_income
    elsif @exchange[:exchange_type] == "Euro"
      euro_quotation = @exchange[:euro_quotation]
      initial_income = @exchange[:initial_income]
      reais = euro_quotation*initial_income
    end
    reais = reais - discount
    return reais
  end

  def discount
    iof_tax = 0.38
    initial_income = @exchange[:initial_income]
    discount = (iof_tax/100)*initial_income
    return discount
  end

  # GET /exchanges/new
  def new
    @exchange = Exchange.new
    json_request
  end

  # GET /exchanges/1/edit
  def edit
  end

  # POST /exchanges
  def create
    @exchange = Exchange.new(exchange_params)

    respond_to do |format|
      if @exchange.save
        format.html { redirect_to @exchange, notice: 'Exchange was successfully created.' }
        format.json { render :show, status: :created, location: @exchange }
      else
        format.html { render :new }
        format.json { render json: @exchange.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exchanges/1
  def update
    respond_to do |format|
      if @exchange.update(exchange_params)
        format.html { redirect_to @exchange, notice: 'Exchange was successfully updated.' }
        format.json { render :show, status: :ok, location: @exchange }
      else
        format.html { render :edit }
        format.json { render json: @exchange.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exchanges/1
  def destroy
    @exchange.destroy
    respond_to do |format|
      format.html { redirect_to wallets_path, notice: 'Exchange was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def json_request
    uri = URI.parse("http://developers.agenciaideias.com.br/cotacoes/json")

    http = Net::HTTP.new(uri.host, uri.port)
    request = Net::HTTP::Get.new(uri.request_uri)

    response = http.request(request)

    if response.code == "200"
      result = JSON.parse(response.body)
      @exchange.update_attributes(:dollar_quotation => result["dolar"]["cotacao"])
      @exchange.update_attributes(:euro_quotation => result["euro"]["cotacao"])
      @exchange.update_attributes(:variation_dollar => result["dolar"]["variacao"]) 
      @exchange.update_attributes(:variation_euro => result["euro"]["variacao"]) 
      @exchange.update_attributes(:initial_dollar_quotation => @exchange[:dollar_quotation])
      @exchange.update_attributes(:initial_euro_quotation => @exchange[:euro_quotation])
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exchange
      @exchange = Exchange.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def exchange_params
      params.require(:exchange).permit(:name, :exchange_type, :initial_income, :wallet_id, :dollar_quotation)
    end
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/views/exchanges/_form.html.erb
<%= form_for(@exchange) do |f| %>
  <% if @exchange.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exchange.errors.count, "error") %> prohibited this exchange from being saved:</h2>

      <ul>
      <% @exchange.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
   <b> <%= f.label "Cotação de compra em Real" %></b><br>
    <%= f.label :dollar_quotation,"Dolar:  #{@exchange[:dollar_quotation]} Variation:  #{@exchange[:variation_dollar]}" %><br>
    <%= f.label :euro_quotation,"Euro:  #{@exchange[:euro_quotation]} Variation:  #{@exchange[:variation_euro]}" %><br><br>

  <div class="field">
    <b><%= f.label :exchange_type, "Escolha o tipo de câmbio" %></b><br>
    <%= f.select :exchange_type, ['Dolar', 'Euro'] %>
  </div>

  <div class="field">
    <%= f.label :name, "Nome" %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :initial_income, "Valor de compra da moeda:" %><br>
    <%= f.text_field :initial_income %>
  </div>

  <div class="field">
    <%= f.label :wallet_id, "Carteira" %><br>
    <%= f.number_field :wallet_id %>
  </div>

  <div class="actions">
    <%= f.submit "Enviar"%>
  </div>
<% end %>

app/views/exchanges/edit.html.erb
<h1>Editar Câmbio</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @exchange %> |
<%= link_to 'Voltar', wallets_path %>

app/views/exchanges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Câmbios</h1>

<table>
  <thead>
    <tr>
      <th>Tipo de Câmbio</th>
      <th>Valor do Invest. Inicial</th>
      <th>Data de Compra</th>
      <th>Carteira</th>
      <th colspan="3"></th>
    </tr>
  </thead>

   <tbody>
    <% @exchanges.each do |exchange| %>
      <tr>
        <td><%= exchange.exchange_type %></td>
        <td><%= exchange.initial_income %></td>
        <td><%= exchange.created_at %></td>
        <td><%= exchange.wallet.name %></td>
        <td><%= link_to 'Exibir', exchange %></td>
        <td><%= link_to 'Editar', edit_exchange_path(exchange) %></td>
        <td><%= link_to 'Apagar', exchange, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo', new_exchange_path %>
<br>
<%= link_to 'Voltar', wallets_path %>

app/views/exchanges/new.html.erb
<h1>Novo Câmbio</h1>

<%= render 'form' %>

<%= link_to 'Voltar', wallets_path %>

app/views/exchanges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo de Câmbio:</strong>
  <%= @exchange.exchange_type %>
</p>

<p>
  <strong>Valor do Invest. Inicial:</strong>
  <%= @exchange.initial_income %>
</p>

<p>
  <strong>Data de Compra:</strong>
  <%= @exchange.created_at %>
</p>

<p>
  <strong>Valor bruto inical em Reais:</strong>
  <%= convert %>
</p>

<p>
  <strong>Desconto:</strong>
  <%= discount %>
</p>


<p>
  <strong>Valor líquido atual em Reais:</strong>
  <%= convert_current_income %>
</p>




<%= link_to 'Editar', edit_exchange_path(@exchange),  class: 'button info tiny' %> |
<%= link_to 'Voltar', exchanges_path,  class: 'button info tiny' %>