config/routes.rb
Rails.application.routes.draw do
  resources :direct_treasuries
  resources :exchanges
  
  resources :stocks do
    member do
      get :stocks_movimentation
    end
    
    collection do
      get :stocks_list
    end
  end
  
  resources :investment_funds
  resources :wallets do
    resources :investment_funds
  end 
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  root to: 'pages#home'
  get '/home', to: 'pages#home', as: :home

  get "/direct_treasuries/simulate/:id" => "direct_treasuries#simulate", :as => 'simulate_direct_treasury'
  get "/analysis/index " => "analysis#index", :as => 'analysis_index'
  get "/questionnaire/index" => "questionnaire#index", :as => 'questionnaire_index'
  post "/questionnaire/questionnaire_result" => "questionnaire#questionnaire_result", :as => 'questionnaire_result'
  get "/questionnaire/user_investment_profile" => "questionnaire#user_investment_profile", :as => 'investment_profile_result'	
  

end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :wallet

  def gross_income
   
      initial = self[:initial_income] 
      current = self[:current_income] 
      
      return (current - initial) * self[:amount]  
  end

  def brokerage
    initial = self[:initial_income] * self[:amount]
    
    brokerage_tax_low = 0.0025
    brokerage_tax_high = 0.0020

    if initial > 0.01 and initial < 50000
      brokerage = initial * brokerage_tax_low
      return brokerage
    elsif initial > 50000
      brokerage = initial * brokerage_tax_high
      return brokerage
    end
  end

  def  emoluments
     initial = self[:initial_income] * self[:amount]
     
     emoluments_tax = 0.000325

    return (initial)*emoluments_tax
  end

  def custody
      current = self[:current_income] * self[:amount]
      
      free = 0

      custody_tax_low = 0.000132
      custody_tax_high = 0.000076

      if current > 0.01 and current < 300000 # menor que 300 mil insento
        return free
      elsif current > 300000 and current < 1000000 # entre 300 mil e 1 milhão 
        return current * custody_tax_low
      elsif current > 1000000 and 10000000 # entre 1 milhão e 10 milhão
        return current * custody_tax_high
      end 
  end

  def income_tax 

    current = self[:current_income] * self[:amount]
    
    liquid_income = gross_income - (custody + emoluments + brokerage) 
    
    free = 0
    total_sale = self[:current_income] * self[:amount]
    income_tax = 0.15

    if total_sale > 20000
      return liquid_income * income_tax
    else
      return free
    end
  end

  def liquid_income

    return liquid_income = gross_income - (income_tax + custody + emoluments + brokerage )
  end

  def total_liquid_income
    all_liquid_income
    stocks = Stocks.all
    stocks.each do |stock|
      all_liquid_income =+ stock.liquid_income
    end
    return all_liquid_income 
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
    @stock = Stock.find(params[:id])
  end

  def stocks_list
    @stocks = Stock.all
  end

  def stocks_movimentation
    @stock_moviment = Stock.find(params[:id])
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:name, :initial_income, :current_income, :buy_date, :buy_tax, :amount, :wallet_id, :closing_price, :closing_date)
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
<%= form_for(@stock) do |f| %>
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% @stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nome" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :initial_income, "Valor do Invest. Inicial" %><br>
    <%= f.number_field :initial_income, :step => 0.01 %>
  </div>
  <div class="field">
    <%= f.label :current_income, "Valor Atual" %><br>
    <%= f.number_field :current_income, :step => 0.01 %>
  </div>
  <div class="field">
    <%= f.label :buy_date, "Data de Compra" %><br>
    <%= f.datetime_select :buy_date %>
  </div>
  <div class="field">
    <%= f.label :buy_tax, "Taxa de Compra" %><br>
    <%= f.number_field :buy_tax, :step => 0.01 %>
  </div>
  <div class="field">
    <%= f.label :amount, "Quantidade" %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :wallet_id, "Carteira" %><br>
    <%= f.number_field :wallet_id %>
  </div>
  <div class="actions">
    <%= f.submit "Enviar" %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editar Bolsa de Valores</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @stock %> |
<%= link_to 'Voltar', wallets_path %>

app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bolsa de Valores</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Receita Inicial</th>
      <th>Receita Atual</th>
      <th>Data de Compra</th>
      <th>Taxa de Compra</th>
      <th>Quantidade</th>
      <th>Carteira</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.name %></td>
        <td><%= stock.initial_income %></td>
        <td><%= stock.current_income %></td>
        <td><%= stock.buy_date %></td>
        <td><%= stock.buy_tax %></td>
        <td><%= stock.amount %></td>
        <td><%= stock.wallet.name %></td>
        <td><%= link_to 'Exibir', stock %></td>
        <td><%= link_to 'Editar', edit_stock_path(stock) %></td>
        <td><%= link_to 'Apagar', stock, method: :delete, data: { confirm: 'Tem Certeza?' } %></td>
        <td><%= link_to 'Movimento', stocks_movimentation_stock_path(stock) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Bolsa', new_stock_path %></br>
<%= link_to 'Voltar', wallets_path %>

app/views/stocks/new.html.erb
<h1>Nova Bolsa de Valores</h1>

<%= render 'form' %>

<%= link_to 'Voltar', wallets_path, class: 'button info tiny' %>

app/views/stocks/show.html.erb
<div class="row" > 
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @stock.name %>
</p>

<p>
  <strong>Receita Inicial:</strong>
  <%= @stock.initial_income %>
</p>

<p>
  <strong>Receita Atual</strong>
  <%= @stock.current_income %>
</p>

<p>
  <strong>Data de Compra:</strong>
  <%= @stock.buy_date %>
</p>

<p>
  <strong>Taxa de Compra:</strong>
  <%= @stock.buy_tax %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @stock.amount %>
</p>

<p>
  <strong>Carteira:</strong>
  <%= @stock.wallet_id %>
</p>


<%= link_to 'Editar', edit_stock_path(@stock), class: 'button info tiny' %> |
<%= link_to 'Voltar', stocks_path, class: 'button info tiny' %>

<br>
<p>
<strong>Veja a movimentação da sua Bolsa de Valores aqui! </strong>
</p>
<%= link_to 'Movimentação', stocks_movimentation_stock_path(@stock) %>

app/views/stocks/stocks_list.html.erb
<p id="notice"><%= notice %></p>
<div class="row" > 
<h1>Movimentação da Bolsa de Valores</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Receita Inicial</th>
      <th>Receira Atual</th>
      <th>Quantidade</th>
      <th>Receita Bruta</th>
      <th>Receita Bruta</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.name %></td>
        <td><%= stock.initial_income %></td>
        <td><%= stock.current_income %></td>
        <td><%= stock.amount %></td>
        <td><%= stock.gross_income %></td>
        <td><%= stock.liquid_income %></td> 
      </tr>
    <% end %>
     
  </tbody>
</table>

<br>

app/views/stocks/stocks_list_html.erb
<p id="notice"><%= notice %></p>
<div class="row" > 
<h1>Stocks Movimentation</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Initial Income</th>
      <th>Current Income</th>
      <th>Amount</th>
      <th>Gross Income</th>
      <th>Liquid Income</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.name %></td>
        <td><%= stock.initial_income %></td>
        <td><%= stock.current_income %></td>
        <td><%= stock.amount %></td>
        <td><%= stock.gross_income %></td>
        <td><%= stock.liquid_income %></td> 
      </tr>
    <% end %>
     
  </tbody>
</table>

<br>

app/views/stocks/stocks_movimentation.html.erb
<p id="notice"><%= notice %></p>
<div class="row" > 

<h1> Movimentação <%= @stock_moviment.name%></h1>

<p>
 <strong>Receita Bruta:</strong>
 <%= @stock_moviment.gross_income.round(2) %>  R$ 
</p>

<p>
  <strong>Receita Líquida:</strong>
 <%= @stock_moviment.liquid_income.round(2) %> R$
</p>

<table>
  <thead>
    <tr>
      <th>Corretagem</th>
      <th>Lucro</th>
      <th>Custódia</th>
      <th>Imposto de Renda</th>
    </tr>
  </thead>  
  <tbody>
      <tr>
        <td><%= @stock_moviment.brokerage.round(2)  %> R$</td>
        <td><%= @stock_moviment.emoluments.round(2) %> R$</td>
        <td><%= @stock_moviment.custody.round(2)  %> R$</td>
        <td><%= @stock_moviment.income_tax.round(2) %> R$</td>
      </tr>     
  </tbody>
</table>

<%= link_to 'Voltar', stocks_path, class: 'button info tiny' %>