config/routes.rb
Rails.application.routes.draw do
  resources :direct_treasuries
  resources :exchanges
  
  resources :stocks do
    member do
      get :stocks_movimentation
    end
    
    collection do
      get :stocks_list
    end
  end
  
  resources :investment_funds
  resources :wallets do
    resources :investment_funds
  end 
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  root to: 'pages#home'
  get '/home', to: 'pages#home', as: :home

  get "/direct_treasuries/simulate/:id" => "direct_treasuries#simulate", :as => 'simulate_direct_treasury'
  get "/analysis/index " => "analysis#index", :as => 'analysis_index'
  get "/questionnaire/index" => "questionnaire#index", :as => 'questionnaire_index'
  post "/questionnaire/questionnaire_result" => "questionnaire#questionnaire_result", :as => 'questionnaire_result'
  get "/questionnaire/user_investment_profile" => "questionnaire#user_investment_profile", :as => 'investment_profile_result'	
  

end

app/models/wallet.rb
class Wallet < ActiveRecord::Base
  belongs_to :user
  has_many :investment_fund
  has_many :stock
  has_many :exchange
  has_many :direct_treasury
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :set_wallet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /wallets
  # GET /wallets.json
  def index
    @wallets = Wallet.where("user_id = ?", current_user)
  end

  # GET /wallets/1
  # GET /wallets/1.json
  def show
  end

  # GET /wallets/new
  def new
    @wallet = Wallet.new
  end

  # GET /wallets/1/edit
  def edit
  end

  # POST /wallets
  # POST /wallets.json
  def create
    @wallet = Wallet.new(wallet_params)
    @wallet.user_id = current_user.id

    respond_to do |format|
      if @wallet.save
        format.html { redirect_to @wallet, notice: 'Wallet was successfully created.' }
        format.json { render :show, status: :created, location: @wallet }
      else
        format.html { render :new }
        format.json { render json: @wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wallets/1
  # PATCH/PUT /wallets/1.json
  def update
    respond_to do |format|
      if @wallet.update(wallet_params)
        format.html { redirect_to @wallet, notice: 'Wallet was successfully updated.' }
        format.json { render :show, status: :ok, location: @wallet }
      else
        format.html { render :edit }
        format.json { render json: @wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wallets/1
  # DELETE /wallets/1.json
  def destroy
    @wallet.destroy
    respond_to do |format|
      format.html { redirect_to wallets_url, notice: 'Wallet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wallet
      @wallet = Wallet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wallet_params
      params.require(:wallet).permit(:name, :comments, current_user)
    end
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/wallets/_form.html.erb
<%= form_for(@wallet) do |f| %>
  <% if @wallet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wallet.errors.count, "error") %> prohibited this wallet from being saved:</h2>

      <ul>
      <% @wallet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nome" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :comments, "Descrição" %><br>
    <%= f.text_field :comments %>
  </div>

  <div class="actions">
    <%= f.submit "Enviar" %>
  </div>
<% end %>

app/views/wallets/edit.html.erb
<h1>Editar Carteira</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @wallet %> |
<%= link_to 'Voltar', wallets_path %>

app/views/wallets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carteiras de Investimento</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Fundos de Inv.</th>
      <th>Bolsa de Val.</th>
      <th>Câmbios</th>
      <th>Tesouro Direto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @wallets.each do |wallet| %>
    <tr>
        <td><%= wallet.name %>
        <td><%= wallet.comments %></br>

        <td><%= link_to 'Fundos de Investimento', investment_funds_path(:wallet_id => "#{wallet.id}") %></td>
        <td><%= link_to 'Bolsa de Valores', stocks_path(:wallet_id => "#{wallet.id}") %></td>
        <td><%= link_to 'Câmbios', exchanges_path(:wallet_id => "#{wallet.id}") %></td>
        <td><%= link_to 'Tesouro Direto', direct_treasuries_path(:wallet_id => "#{wallet.id}") %></td>
        <td><%= link_to 'Exibir', wallet %></td>
        <td><%= link_to 'Editar', edit_wallet_path(wallet) %></td>
        <td><%= link_to 'Apagar', wallet, method: :delete, data: { confirm: 'Tem Certeza?' } %></td>
      </tr>
    <% end %>

   </tbody>

</table>

<br>

<%= link_to 'Nova Carteira', new_wallet_path %>

app/views/wallets/new.html.erb
<h1>Nova Carteira</h1>

<%= render 'form' %>

<%= link_to 'Voltar', wallets_path %>

app/views/wallets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuário:</strong>
  <%= @wallet.user.name %>
</p>
<p>
  <strong>Nome:</strong>
  <%= @wallet.name %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @wallet.comments %>
</p>


<%= link_to 'Editar', edit_wallet_path(@wallet) %> |
<%= link_to 'Voltar', wallets_path %>